### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mudlord** [mudlord/WTFweg#1]
- [ ] commandline support like einweg.
- [ ] support for some form of post process shaders
- [ ] support for some form of audio filtering
- [ ] per-game settings
- [ ] disk change interface (maybe?)
- [ ] retrokeyboard
- [ ] Add OGL3.3+VK interop for Vulkan hardware contexts? (needs pluggable VK backend)

**Comment by mudlord** [comment]
added CLI support, sorta hidden.

**Comment by mudlord** [comment]
added untested per-game settings with CLI only.

**Comment by mudlord** [comment]
added retrokeyboard.
