### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mudlord** [mudlord/wtfweg#1]
- [ ] post process shaders
- [ ] port over code from foo_dsp_effect for audio DSP
- [ ] MIDI output support
- [ ] finish mouse/keyboard input
- [ ] finish proper borderless widescreen
- [ ] fix up cores that require subcontent (ie MelonDS, ECWolf)
